### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MG577** [xhlove/WVClient3#7]
"D:\WVClient3-main\WVClient3-main\wvclient.py"
Traceback (most recent call last):
  File "D:\WVClient3-main\WVClient3-main\wvclient.py", line 15, in <module>
    from utils import license_protocol_pb2
  File "D:\WVClient3-main\WVClient3-main\utils\license_protocol_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

I am getting this error .. any solution ??

**Comment by MG577** [comment]
pip install --upgrade protobuf


working after upgrading
